#!/usr/bin/env python3
"""Generate reviewable documentation reference pages from public contracts."""

from __future__ import annotations

import argparse
import html
import importlib
import inspect
import json
from enum import Enum
from pathlib import Path
from types import ModuleType
from typing import Any, get_origin

from pydantic import BaseModel

from anatomize.version import __version__

PUBLIC_NAMESPACES = {
    "anatomize.review": "High-level application, capability negotiation, artifact gateway, and rendering.",
    "anatomize.index": "Deterministic baseline repository facts.",
    "anatomize.evidence": "Canonical evidence, completeness, conflict, provenance, and merge contracts.",
    "anatomize.identity": "Portable identities, coordinates, and cross-provider reconciliation.",
    "anatomize.providers": "Data-only provider envelopes, normalization, and conformance.",
    "anatomize.sessions": "Portable sessions and immutable recoverable generations.",
    "anatomize.dossiers": "Task targets, proof roles, budgets, selection, and expansion.",
    "anatomize.temporal": "Exact source states and evidence-wide comparison.",
    "anatomize.lifecycle": "Similarity, decisions, implementation intent, change, and closure.",
    "anatomize.semantic": "Captured language-server semantic artifacts.",
    "anatomize.diagnostics": "Bounded SARIF 2.1.0 diagnostics.",
    "anatomize.research": "R, notebooks, workflows, data, environments, and provenance.",
}


def _schema_models() -> dict[str, type[BaseModel]]:
    from anatomize.dossiers import Dossier
    from anatomize.evidence import RepositoryEvidence
    from anatomize.lifecycle import (
        ChangeDossier,
        ClosureReport,
        ConsolidationDossier,
        DecisionOverlay,
        ImplementationIntent,
        OverlayEvaluation,
        SimilarityArtifact,
    )
    from anatomize.review import ArtifactCheck, DossierExchange
    from anatomize.sessions import ReviewSessionBundle
    from anatomize.temporal import StateManifest

    return {
        "artifact_check": ArtifactCheck,
        "change_dossier": ChangeDossier,
        "closure_report": ClosureReport,
        "consolidation_dossier": ConsolidationDossier,
        "decision_overlay": DecisionOverlay,
        "dossier_exchange": DossierExchange,
        "evidence": RepositoryEvidence,
        "implementation_intent": ImplementationIntent,
        "overlay_evaluation": OverlayEvaluation,
        "session": ReviewSessionBundle,
        "similarity": SimilarityArtifact,
        "state_manifest": StateManifest,
        # The dossier is embedded by DossierExchange but remains a public
        # lower-level contract useful to provider and consumer authors.
        "dossier": Dossier,
    }


def _capabilities() -> dict[str, Any]:
    from anatomize.review import review_capabilities

    return review_capabilities()


def _capabilities_page(capabilities: dict[str, Any]) -> str:
    operations = "\n".join(f"- `{value}`" for value in capabilities["operations"])
    profiles = "\n".join(f"- `{value}`" for value in capabilities["profiles"])
    targets = "\n".join(f"- `{value}`" for value in capabilities["target_kinds"])
    schemas = "\n".join(
        f"| `{name}` | `{version}` | [JSON Schema](schemas/{name}.schema.json) |"
        for name, version in sorted(capabilities["schemas"].items())
    )
    interaction = "\n".join(
        f"| {name.replace('_', ' ').title()} | {value} |"
        for name, value in sorted(capabilities["interaction"].items())
    )
    return f"""# Generated capabilities

<!-- Generated by scripts/generate_documentation.py. Do not edit by hand. -->

This page is generated from `anatomize.review.review_capabilities` in
Anatomize `{__version__}`. Regenerate it whenever the public application
contract changes.

| Contract | Value |
| --- | --- |
| Application | `{capabilities['application']}` |
| Application API | `{capabilities['application_api_version']}` |

## Operations

{operations}

## Lifecycle profiles

{profiles}

## Target kinds

{targets}

## Current operation schemas

| Capability | Version | Schema |
| --- | --- | --- |
{schemas}

The public dossier schema is also available as
[`dossier.schema.json`](schemas/dossier.schema.json). Exact option spelling
remains in [the public reference](../REFERENCE.md) and command help.

## Interaction policy

| Property | Contract |
| --- | --- |
{interaction}
"""


def _public_api_page() -> str:
    sections: list[str] = [
        "# Generated Python API inventory",
        "",
        "<!-- Generated by scripts/generate_documentation.py. Do not edit by hand. -->",
        "",
        f"This inventory is generated from each public namespace's `__all__` under Anatomize `{__version__}`.",
        "Names absent from `__all__` are implementation details.",
        "",
        "For most integrations, start with `anatomize.review.ReviewApplication` rather than lower-level builders.",
        "",
    ]
    for module_name, purpose in PUBLIC_NAMESPACES.items():
        module = importlib.import_module(module_name)
        exports = _exports(module)
        sections.extend(
            [
                f"## `{module_name}`",
                "",
                purpose,
                "",
                f"Exported names: {len(exports)}.",
                "",
                "| Name | Kind | Summary |",
                "| --- | --- | --- |",
            ]
        )
        for name in exports:
            value = getattr(module, name)
            sections.append(f"| `{name}` | {_kind(value)} | {_summary(value)} |")
        sections.append("")
    return "\n".join(sections).rstrip() + "\n"


def _exports(module: ModuleType) -> list[str]:
    exports = getattr(module, "__all__", None)
    if not isinstance(exports, list) or not all(isinstance(value, str) for value in exports):
        raise ValueError(f"{module.__name__} must expose one string-only __all__ list")
    if len(exports) != len(set(exports)):
        raise ValueError(f"{module.__name__} contains duplicate public exports")
    missing = [name for name in exports if not hasattr(module, name)]
    if missing:
        raise ValueError(f"{module.__name__} declares missing exports: {missing}")
    return exports


def _kind(value: object) -> str:
    if inspect.isclass(value):
        return "class"
    if inspect.isfunction(value):
        return "function"
    if get_origin(value) is not None:
        return "type alias"
    return "constant"


def _summary(value: object) -> str:
    if get_origin(value) is not None:
        return "Public type alias."
    if not inspect.isclass(value) and not inspect.isfunction(value):
        if isinstance(value, (str, int, float, bool)) or value is None:
            rendered = repr(value)
            if len(rendered) <= 100:
                return html.escape(f"Value: `{rendered}`.", quote=False)
        return f"Public value of type `{html.escape(type(value).__name__)}`."
    if inspect.isclass(value) and issubclass(value, Enum):
        members = ", ".join(f"`{html.escape(str(item.value), quote=False)}`" for item in value)
        if len(members) <= 180:
            return f"Enum values: {members}."
        return f"Public enum with {len(value)} values."
    documentation = value.__doc__ if inspect.isclass(value) else inspect.getdoc(value)
    if inspect.isclass(value) and not documentation and issubclass(value, BaseModel):
        documentation = f"Public model with {len(value.model_fields)} fields."
    first_line = documentation.splitlines()[0] if documentation else "Public exported value."
    if inspect.isfunction(value):
        try:
            signature = str(inspect.signature(value))
        except (TypeError, ValueError):
            signature = "(...)"
        safe_signature = signature.replace("|", "&#124;")
        safe_documentation = html.escape(first_line, quote=False).replace("|", "&#124;")
        return f"`{safe_signature}` — {safe_documentation}"
    return html.escape(first_line, quote=False).replace("|", "&#124;")


def _schemas_page(models: dict[str, type[BaseModel]], capabilities: dict[str, Any]) -> str:
    rows: list[str] = []
    capability_schemas = capabilities["schemas"]
    for name, model in sorted(models.items()):
        version = capability_schemas.get(name, "public embedded contract")
        rows.append(f"| `{name}` | `{model.__name__}` | `{version}` | [Download](schemas/{name}.schema.json) |")
    return f"""# Generated JSON Schemas

<!-- Generated by scripts/generate_documentation.py. Do not edit by hand. -->

These schemas are generated from the installed Anatomize `{__version__}`
Pydantic models in serialization mode. They are review and integration aids;
runtime validation and `review capabilities` remain authoritative.

| Contract | Python model | Version | Schema |
| --- | --- | --- | --- |
{chr(10).join(rows)}

Artifacts use exact current schemas. Anatomize does not guess compatibility or
migrate older payloads; regenerate them with the current producer.
"""


def generated_files() -> dict[Path, bytes]:
    capabilities = _capabilities()
    models = _schema_models()
    advertised = set(capabilities["schemas"])
    missing = advertised.difference(models)
    if missing:
        raise ValueError(f"No generated JSON Schema model for advertised capabilities: {sorted(missing)}")
    files = {
        Path("capabilities.md"): _capabilities_page(capabilities).encode(),
        Path("python-api.md"): _public_api_page().encode(),
        Path("schemas.md"): _schemas_page(models, capabilities).encode(),
    }
    for name, model in sorted(models.items()):
        payload = json.dumps(
            model.model_json_schema(mode="serialization"),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        files[Path("schemas") / f"{name}.schema.json"] = (payload + "\n").encode()
    return files


def materialize(output_dir: Path, *, check: bool) -> None:
    expected = generated_files()
    failures: list[str] = []
    for relative_path, content in expected.items():
        destination = output_dir / relative_path
        existing = destination.read_bytes() if destination.is_file() else None
        if existing == content:
            continue
        if check:
            failures.append(relative_path.as_posix())
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(content)
    actual = {
        path.relative_to(output_dir)
        for path in output_dir.rglob("*")
        if path.is_file()
    } if output_dir.is_dir() else set()
    unexpected = sorted(actual.difference(expected), key=lambda value: value.as_posix())
    if unexpected:
        if check:
            failures.extend(f"unexpected:{path.as_posix()}" for path in unexpected)
        else:
            for relative_path in unexpected:
                (output_dir / relative_path).unlink()
    if failures:
        raise ValueError("Generated documentation is stale: " + ", ".join(failures))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("docs/generated"))
    parser.add_argument("--check", action="store_true", help="Fail instead of updating stale generated files.")
    arguments = parser.parse_args()
    materialize(arguments.output_dir, check=arguments.check)
    action = "Verified" if arguments.check else "Generated"
    print(f"{action} documentation references: {arguments.output_dir}")


if __name__ == "__main__":
    main()
